# Site settings
title: "North End Tiny-Home Living"
description: > 
  Small, newly-renovated apartment with private roofdeck and fantastic views in Boston's North End
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown


captions:
  21: View of the Old North church from the roof deck
  23: Summer fireworks visible from the roof
